[versions]

coreTesting = "2.2.0"
kotlinxCoroutinesTest = "1.7.3"
mockitoCore = "4.4.0"
mockitoInline = "4.4.0"

[libraries]

androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }

[plugins]

